<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
$resources = array('RES_GUEST' => 'Гость', 'RES_SETTINGS_APPLIED' => 'Настройки успешно применены!',
    'RES_NO_FILE_CHOSEN' => 'Вы не выбрали файл',
    'RES_FILE_TOO_LARGE' => 'Размер файла не соответствует нормам',
    'RES_FILE_HAS_WRONG_TYPE' => 'Допускается загрузка только картинок JPG, PNG и GIF',
    'RES_TRY_AGAIN' => 'Что-то пошло не так. Попытайтесь загрузить файл ещё раз.',
    'RES_FILE_UPLOADED' => 'Файл загружен: ',
    'RES_SITENAME_IS_EMPTY' => 'Введите название сайта!',
    'RES_DOMAIN_IS_NOT_CORRECT' => 'Домен введен неправильно!',
    'RES_ADMIN_EMAIL_IS_NOT_CORRECT' => 'E-mail администратора введен неправильно!',
    'RES_POSTS_ON_PAGE_VALUE_IS_NOT_CORRECT' => 'Количество записей на странице должно быть целым числом!',
    'RES_YANDEX_METRICA_IS_NOT_CORRECT' => '"Яндекс.Метрика ID" должен быть целым числом!',
    'RES_LOGIN_IS_EMPTY' => 'Вы не ввели логин',
    'RES_LOGIN_IS_INCORRECT' => 'Вы неправильно ввели логин',
    'RES_PASSWORD_IS_EMPTY' => 'Вы не ввели пароль',
    'RES_PASSWORD_IS_INCORRECT' => 'Вы неправильно ввели пароль',
    'RES_PASSWORDS_DONT_MATCH' => 'Пароли не совпадают!',
    'RES_AUTH_SUCCESS' => 'Вы успешно авторизовались!',
    'RES_AUTH_FAILURE' => 'Неправильный логин или пароль!',
    'RES_USER_ALREADY_EXISTS' => 'Такой пользователь уже существует!',
    'RES_EMAIL_ALREADY_EXISTS' => 'Пользователь с таким e-mail уже существует!',
    'RES_PASSWORD_CONFIRMATION_IS_EMPTY' => 'Вы не ввели подтверждение пароля',
    'RES_PASSWORD_CONFIRMATION_IS_NOT_CORRECT' => 'Вы неправильно ввели подтверждение пароля',
    'RES_EMAIL_IS_NOT_CORRECT' => 'E-mail введен неправильно',
    'RES_EMAIL_IS_EMPTY' => 'Вы не ввели E-mail',
    'RES_SIGNUP_SUCCESS' => 'Для завершения регистрации перейдите по ссылке, высланой вам по e-mail',
    'RES_UNEXPECTED_ERROR' => 'Непредвиденная ошибка!',
    'RES_ENTER_CAPTION' => 'Введите, пожалуйста, заголовок!',
    'RES_ENTER_BODY' => 'Введите, пожалуйста, текст сообщения!',
    'RES_ENTER_PICTURE' => 'Добавьте, пожалуйста, изображение!',
    'RES_POST_IS_ADDED' => 'Пост успешно добавлен!',
    'RES_USERS_HAVE_BEEN_DELETED' => 'Выбранные пользователи, а также вся связанная с ними информация были удалены!',
    'RES_ADMIN_RESTICTED_ACCESS' => 'Доступ к запрошенной странице имеют только администраторы!',
    'RES_AUTH_IS_REQUIRED' => 'Доступ к запрошенной странице имеют только авторизированные пользователи!',
    'RES_COMMENT_COULD_NOT_BE_EMPTY' => 'Комментарий не может быть пустым!',
    'RES_COMMENT_HAS_BEEN_ADDED' => 'Комментарий успешно добавлен!',
    'RES_COMMENTS_HAVE_BEEN_DELETED' => 'Выделенные комментарии успешно удалены!',
    'RES_PLEASE_SELECT_COMMENTS' => 'Выделите необходимые комментарии для удаления!',
    'RES_PLEASE_SELECT_USERS' => 'Выделите необходимых пользователей для удаления!',
    'RES_ADD_TO_MENU' => 'Добавить в меню',
    'RES_REMOVE_FROM_MENU' => 'Удалить из меню',
    'RES_CHOOSE_ACTION' => 'Пожалуйста, выберите действие!',
    'RES_POST_HAS_BEEN_DELETED' => 'Пост успешно удален!',
    'RES_POST_HAS_BEEN_UPDATED' => 'Пост успешно обновлён!',
    'RES_POST_HAS_BEEN_ADDED_TO_MENU' => 'Пост успешно добавлен в меню!',
    'RES_POST_HAS_BEEN_DELETED_FROM_MENU' => 'Пост успешно удалён из меню!',
    'RES_ACCOUNT_IS_NOT_CONFIRMED' => 'Для корректной авторизации требуется подтверждение e-mail, введенного при регистрации. Ссылка для подтверждения была выслана на Ваш e-mail.',
    'RES_EMAIL_HAS_BEEN_ALREADY_CONFIRMED' => ': e-mail пользователя уже был подтвержден!',
    'RES_EMAIL_HAS_BEEN_CONFIRMED' => 'Ваш e-mail был успешно подтвержден!',
    'RES_MAIN_PAGE' => 'Главная - ',
    'RES_AUTHORISATION' => 'Авторизация - ',
    'RES_REGISTRATION' => 'Регистрация - ',
    'RES_NEW_POST' => 'Новая запись - ',
    'RES_PROFILE' => 'Профиль - ',
    'RES_SETTINGS' => 'Настройки - ',
    'RES_REPORT' => 'Отчёт - ',
    'ERR_404' => 'Ошибка 404: Страница не найдена! - ',
    'ERR_CONNECT_FAILED' => 'Невозможно установить соединение с базой данных! Проверьте настройки в файле config.php и попробуйте снова!'
);
?>
